---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-pv
  labels:
    name: sharedvolume
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: sharedvolume
